### ISSUE TITLE
[BUG] Cypress test failures

### ISSUE THREAD

**Issue by zhongnansu** [opensearch-project/dashboards-reports#107]
**Describe the bug**
- [x] Create scheduled report definition failure: the test fails
- [ ] Create on-demand report defintion failure: the test can pass but never create a report instance, which will lead to the failure of download from report table test in `download.spec`

**To Reproduce**
1. spin up Opensearch and Dashboards with reporting installed on both
2. `yarn cypress:run`
3. check test reports

**Expected behavior**

**Plugins**
Please list all plugins currently enabled.

**Screenshots**

**Host/Environment (please complete the following information):**

**Additional context**

**Comment by davidcui-amzn** [comment]
Fixed in #123
