### ISSUE TITLE
security_tenant and embed parameteres are mutually exclusive

### ISSUE THREAD

**Issue by zhongnansu** [opensearch-project/dashboards-reports#14]
**Is your feature request related to a problem? Please describe.**

**Describe the solution you'd like**

**Describe alternatives you've considered**

**Additional context**

--- 

Hi

In my application, I embed Kibana dashboards and other pages in iframes.

In order to select tenant, we add security_tenant parameter to the url (before the # anchor)
To embed the Kibana page (remove the upper and leftside menus), we use embed=true (after the # anchor)

Each of those parameters works separately, but when we put them together the embed parameter is not working

Here is a sample of url in iframe 

`https://kibana_host:443/app/opendistro_kibana_reports?security_tenant=my-tenant#/?embed=true`

This issue is submitted by @WassimDhib
https://github.com/opendistro-for-elasticsearch/kibana-reports/issues/279

**Comment by anirudha** [comment]
we dont support iframe for reporting, could you please describe your usecase and reopen this issue. thanks
