### ISSUE TITLE
Multibyte characters in in visuals get garbled for pdf/png report

### ISSUE THREAD

**Issue by zhongnansu** [opensearch-project/dashboards-reports#154]
I used these characters for test and found that this may occurs when using more than 3-bytes (UTF-8 encoding) characters. These characters look nice through when using browser.

2 bytes  - ÁÂÃÄ
3 bytes - あいうえお
4 bytes - 🀀🀁🀂🀃

- Browser
![image](https://user-images.githubusercontent.com/32652829/133150745-1fb4184e-3a5e-4b14-944e-2e1a8ad0a9c6.png)
 

- Reports:
![image](https://user-images.githubusercontent.com/32652829/133150792-64cb7217-fcb6-4b52-822f-ff675decfd36.png)

![image](https://user-images.githubusercontent.com/32652829/133150526-f006eced-3a95-44b7-a75b-1b02af0db8bc.png)

Also chinsese characters have the same issue.

**Comment by zhongnansu** [comment]
@joshuali925 I remember you said this may be related to fonts lib used in Chromium? Could you share a bit more details

**Comment by zhongnansu** [comment]
some ref: https://www.elastic.co/guide/en/kibana/current/reporting-troubleshooting.html#reporting-troubleshooting-text-incorrect

**Comment by joshuali925** [comment]
If the server does not have corresponding fonts installed, chromium won't be able to render them and they'll look like empty rectangles. #69 is the same issue and can be fixed by `sudo yum install -y google-noto-emoji-color-fonts.noarch` on centos for example
