### ISSUE TITLE
cluster:admin/opendistro/reports/definition/delete wasn't rebranded

### ISSUE THREAD

**Issue by JeffAshton** [opensearch-project/dashboards-reports#187]
**Is your feature request related to a problem? Please describe.**

`cluster:admin/opendistro/reports/definition/delete` was missed during the OpenSearch rebranding.  Leaving it an outcast from the other permissions:

https://github.com/opensearch-project/dashboards-reports/blob/b62ba6e551a82624db44a1cb06028ff269d19ec7/reports-scheduler/src/main/kotlin/org/opensearch/reportsscheduler/action/DeleteReportDefinitionAction.kt#L54

![image](https://user-images.githubusercontent.com/12101120/138502057-8b6b0bcb-fd2a-4f03-8b0d-315b20a7da67.png)

**Describe the solution you'd like**

Align it with all the other `cluster:admin/opensearch/reports/*` permissions.

**Comment by anirudha** [comment]
closed as a dupe

**Comment by zhongnansu** [comment]
Refer to the discussion in #223
