### ISSUE TITLE
Add MacOS Support

### ISSUE THREAD

**Issue by dblock** [opensearch-project/dashboards-reports#192]
Coming from https://github.com/opensearch-project/opensearch-plugins/issues/96, add MacOS (Darwin) support.

- [ ] Passing CI on MacOS
- [ ] Documentation

**Comment by derek-ho** [comment]
Merged the PR

**Comment by derek-ho** [comment]
@joshuali925 @rupal-bq can one of you folks close this issue? I don't have access....

**Comment by joshuali925** [comment]
closed by #504
