### ISSUE TITLE
Default CI Java Version to Java 11, run tests on 8, 14 and 17

### ISSUE THREAD

**Issue by dblock** [opensearch-project/dashboards-reports#230]
Coming from https://github.com/opensearch-project/opensearch-plugins/issues/64, default CI Java version to 11 (LTS), and run tests on 8, 14 and 17.

- [ ] Change the default Java version for CI in GitHub actions from 14/15 to 11 (LTS).
- [ ] Add Java 8, 14 (used before), and 17 (next LTS) to the CI matrix.
- [ ] Document Java versions in DEVELOPER_GUIDE.md.

**Comment by zhongnansu** [comment]
I tried adding java 8 to the matrix in gitub CI by "setup-java/@v2", I saw the following error. It seems from the [doc](https://github.com/opensearch-project/OpenSearch/blob/main/DEVELOPER_GUIDE.md#jdk-8-and-14) the opensearch core is expecting the compile time java to be at least 11, while for runtime it could be 8, 11, 14. Need some advice from infra on how to add to github action CI. I think it should be similar across plugins

```
* What went wrong:
A problem occurred evaluating root project 'opensearch-reports-scheduler'.
> Failed to apply plugin 'opensearch.opensearchplugin'.
   > Could not create plugin of type 'PluginBuildPlugin'.
      > Could not generate a decorated class for type PluginBuildPlugin.
         > org/opensearch/gradle/plugin/PluginPropertiesExtension has been compiled by a more recent version of the Java Runtime (class file version 54.0), this version of the Java Runtime only recognizes class file versions up to 52.0

```

**Comment by dblock** [comment]
This is expected, we only want to run tests on 8 but compiling on 11 is fine.

**Comment by dblock** [comment]
@davidcui1225  You still need a 1.3.0 build on JDK 8, don't see it in the workflows.

**Comment by davidcui1225** [comment]
> @davidcui1225 You still need a 1.3.0 build on JDK 8, don't see it in the workflows.

Are we pushing back the release date? The code freeze is EOD today, we will only have ~2 hours to get these all merged in.
