### ISSUE TITLE
[BUG] Update observability in url validation

### ISSUE THREAD

**Issue by joshuali925** [opensearch-project/dashboards-reports#232]
**Describe the bug**
Observability plugin url changed from `observability` to `observability-dashboards`, the reporting validation is still expecting observability. 

In-context menu validation will fail and user won't be able to download notebook reports within menu, although they are still able to create and download notebook reports in reporting UI as a workaround.

**To Reproduce**
1. Create a notebook in observability plugin
2. Click on "Reporting actions"
3. Click on "Download PDF" and "Download PNG", network requests will fail with `[query_url]: invalid relative url`
4. Click on "Create report definition" button still works

**Expected behavior**
All buttons should work

**Plugins**
Please list all plugins currently enabled.

**Screenshots**

**Host/Environment (please complete the following information):**

**Additional context**

**Comment by peternied** [comment]
@joshuali925 I am not familiar with the feature, please add repro steps to the template so we can get a sense of the severity of this issue.

**Comment by joshuali925** [comment]
> @joshuali925 I am not familiar with the feature, please add repro steps to the template so we can get a sense of the severity of this issue.

@peternied updated
