### ISSUE TITLE
version bump to 1.3

### ISSUE THREAD

**Issue by zhongnansu** [opensearch-project/dashboards-reports#242]
- [x] dashboards-reports
- [x] opensearch-reports-scheduler

**Comment by anirudha** [comment]
pending changes from dashboads

**Comment by zhongnansu** [comment]
correction: pending meta issues created by Dashboards/Opensearch team https://github.com/opensearch-project/opensearch-build/issues/889

**Comment by zhongnansu** [comment]
closing to not confuse people, this issue and related PR only deals with bumping version. As for release tasks, it's usually more than a version bump, waiting for infra team to create meta issue for each plugin, like always
