### ISSUE TITLE
[BUG] CSV reports will fail when a `date` field is an empty list

### ISSUE THREAD

**Issue by zhongnansu** [opensearch-project/dashboards-reports#262]
**Describe the bug**
- Error message
```
{"statusCode":500,"error":"Internal Server Error","message":"Cannot read property '0' of undefined"}
```

For example

- mapping:
```
{
  "test" : {
    "mappings" : {
      "properties" : {
        "@timestamp" : {
          "type" : "date"
        },
        "dates" : {
          "type" : "date"
        },
        "message" : {
          "type" : "text",
          "fields" : {
            "keyword" : {
              "type" : "keyword",
              "ignore_above" : 256
            }
          }
        }
      }
    }
  }
}
```

- sample data 
```
 {
        "_index" : "test",
        "_type" : "_doc",
        "_id" : "5",
        "_score" : 1.0,
        "_source" : {
          "@timestamp" : "2021-12-17T14:03:21",
          "message" : "first",
          "dates" : [ ]
        }
      },
      {
        "_index" : "test",
        "_type" : "_doc",
        "_id" : "4",
        "_score" : 1.0,
        "_source" : {
          "@timestamp" : "2021-12-17T14:03:21",
          "message" : "first",
          "dates" : [
            "2021-12-17T14:04:55",
            "2021-12-17T14:03:55"
          ]
        }
      },
```

- in Discover
![image](https://user-images.githubusercontent.com/32652829/146615176-99829b42-4b5e-4875-9283-bf2e34f69556.png)

### Root cause
This code is causing the issue.
`if (data._source[dateType])` will pass for an empty list, and failed the following logic. Need to put more restriction on this check. Also, for logic of parsing the only the first elements doesn't seem right. It should parse everything.

https://github.com/opensearch-project/dashboards-reports/blob/main/dashboards-reports/server/routes/utils/dataReportHelpers.ts#L117-L127

**To Reproduce**

**Expected behavior**

**Plugins**
Please list all plugins currently enabled.

**Screenshots**

**Host/Environment (please complete the following information):**

**Additional context**

**Comment by hlosukwakha** [comment]
Just wondering if there are any plans to address this? 

Thanks
