### ISSUE TITLE
[BUG] Replace checked in reports-scheduler/src/test/resources/job-scheduler/opensearch-job-scheduler-1.2.3.0-*.zip with a dynamic dependency

### ISSUE THREAD

**Issue by dblock** [opensearch-project/dashboards-reports#263]
**Describe the bug**

When we increment a version we also need to update job-scheduler by hand.

```
cd job-scheduler
git checkout 1.2
git pull
./gradlew assemble

rm ../dashboards-reports/reports-scheduler/src/test/resources/job-scheduler/*
cp ./build/distributions/opensearch-job-scheduler-1.2.3.0-SNAPSHOT.zip ../dashboards-reports/reports-scheduler/src/test/resources/job-scheduler/
```

This random version of job-scheduler built on my machine is not reliable and will hide bugs.
 
**Expected behavior**
This shouldn't be needed, replace with a dynamic dependency.

**Comment by zhongnansu** [comment]
note: to whoever takes this task

reference from job-scheduler README: Add [this workaround](https://github.com/opensearch-project/job-scheduler/blob/main/sample-extension-plugin/build.gradle#L36) to make sure that job-schedular plugin is correctly installed during integration tests.

**Comment by dblock** [comment]
We have to deal with this in every release? How can we get this prioritized?
