### ISSUE TITLE
Remove jcenter repository

### ISSUE THREAD

**Issue by mch2** [opensearch-project/dashboards-reports#276]
## Description
JCenter has been turned off and should be removed as a referenced repository.

Please Remove any direct dependency on jcenter() within a repositories block in gradle files.

Related: https://github.com/opensearch-project/opensearch-build/issues/1456

**Comment by ps48** [comment]
@mch2 For plugins we have removed jcenter from 1.3.0 and 1.2.4, do we need to backport this further to 1.0 and 1.1?

**Comment by peternied** [comment]
@ps48 We do not need to backport these changes before the latest versions we will create a patch release.

**Comment by peternied** [comment]
It sounds like this work is down - should this issue be closed?

**Comment by ps48** [comment]
@peternied Thanks for the clarification.
