### ISSUE TITLE
Imported Dashboards and Visualizations with custom IDs cannot be exported on-demand.

### ISSUE THREAD

**Issue by inf17101** [opensearch-project/dashboards-reports#281]
**Describe the bug**
If you import a saved objects file via API or Opensearch Dashboard WebUI and set a custom ID for visualizations and the dashboard itself, then the "Reporting" Submenu for on-demand exports is greyed out. So you can click onto "Reporting" on a dashboard view, but the export buttons inside the submenu are greyed out. A report definition can still be created and a report can be downloaded if it was created via reporting definitions, but on-demand report generation does not work like described before.

**To Reproduce**
1. Export an existing dashboard via saved objects API or saved objects menu of the WebUI.
2. Set unique but custom IDs in the ndjson file for every visualization, index pattern and dashboard.
3. Import the changed saved objects file via saved objects API or saved objects menu of the WebUI.
4. Open the dashboard in the WebUI and click on "Reporting".
5. Verify that the custom ID is set (check the browser URI).
6. Now you can see that alle reporting options are unavailable.
7. Clone the imported dashboard via WebUI "Clone" button and save a copy as new dashboard.
8. Now open the cloned dashboard in the WebUI: you can see that a new auto-genearted ID is set for the cloned dashboard and if you click on "reporting", now the buttons are not greyed out anymore and you can export it.

**Expected behavior**
I expect that on-demand export of dashboards and visualizations with custom unique IDs set is supported.
Needed for automation purposes.

**Screenshots**
![image](https://user-images.githubusercontent.com/42932060/149913587-2a03c071-6a9e-4b6f-8375-87e1c23d4835.png)

**Host/Environment (please complete the following information):**
 Linux Ubuntu Server 20.04

Thank you in advance.
Best regards.

**Comment by zhongnansu** [comment]
@inf17101 It seems like a bug, thx for providing the steps to reproduce. We'll follow and try. Meanwhile, I have a question, is this type of issue only for pdf/png report? Do you experience the same thing with saved searches?

**Comment by inf17101** [comment]
@zhongnansu Yes I think too, for saved searches its the same.

![image](https://user-images.githubusercontent.com/42932060/150940610-f29ce300-fb89-4da5-9d79-8e5d3403d7e7.png)

**Comment by joshuali925** [comment]
The code is assuming that saved object ids follows UUID format, causing this issue:
https://github.com/opensearch-project/dashboards-reports/blob/main/dashboards-reports/public/components/context_menu/context_menu.js#L129

will need to update the regex to extract custom object id

**Comment by inf17101** [comment]
@joshuali925: Can you change the regex expression in the code?
