### ISSUE TITLE
Support CSV reports with leading wildcard

### ISSUE THREAD

**Issue by joshuali925** [opensearch-project/dashboards-reports#299]
**Describe the bug**

**To Reproduce**
1. view sample data flights in discover
2. save a query with DQL to be `FlightNum: *1`
3. download csv report
4. UI shows "There was an error generating this report.", response error 
```
{"statusCode":500,"error":"Internal Server Error","message":"Leading wildcards are disabled. See query:allowLeadingWildcards in Advanced Settings.\nFlightNum: *1\n-----------^"}
```

the setting is enabled in advanced settings. looks like leading wildcard queries work if sent by discover, but not reporting

**Comment by theGeorgew** [comment]
This is also affecting OpenSearch clusters running on AWS
