### ISSUE TITLE
Add support for build version qualifiers.

### ISSUE THREAD

**Issue by dblock** [opensearch-project/dashboards-reports#306]
Coming from https://github.com/opensearch-project/opensearch-build/issues/1632, add support for `-Dbuild.version_qualifier=`. 

The distribution build process now supports passing additional optional qualifiers other than the 3 digit versions, e.g. `2.0.0-alpha1`. Add the ability to pass additional qualifier to build scripts, and generate artifacts with a version that includes the qualifier.

**Comment by kavilla** [comment]
Hi @joshuali925, I see you handled the OpenSearch plugin, are you working on the OpenSearch Dashboards side as well. 

Unfortunately for OpenSearch Dashboards we don't have a nice build param as OpenSearch side has [yet](https://github.com/opensearch-project/OpenSearch-Dashboards/issues/1398). You will be able to build and connect successfully to OpenSearch Dashboards `yarn plugin_helpers build --opensearch-dashboards-version=2.0.0-alpha1)` with an OSD plugin `2.0.0.0` but this will fail within the distribution build.

As for `2.0.0-alpha1` we ask plugins to bump their `version` [[here]](https://github.com/opensearch-project/dashboards-reports/blob/main/dashboards-reports/opensearch_dashboards.json#L3) to be `2.0.0.0-alpha1` to be supported within the build distribution.

Let me know if you have any follow up questions.

Thanks!

**Comment by joshuali925** [comment]
@kavilla should `opensearchDashboardsVersion` be `2.0.0-alpha1`? i checked core repo didn't find alpha1 qualifier in its version

```json
{
  "id": "reportsDashboards",
  "version": "2.0.0.0-alpha1",
  "opensearchDashboardsVersion": "2.0.0-alpha1",
```

**Comment by kavilla** [comment]
Up to you but I might share different opinions than others.

My opinion, is that leave `opensearchDashboardsVersion` untouched. You can then utilize OpenSearch Dashboards `main`. Within the build repo we build OpenSearch Dashboards and plugins with a qualifier. This will set OpenSearch Dashboards to be `2.0.0-alpha` and within plugins `"opensearchDashboardsVersion": "2.0.0-alpha1"". So it will be compatible and succeed in the building of distributions.

**Comment by joshuali925** [comment]
I see, so in plugin builds `opensearchDashboardsVersion` can be overridden by build args but `version` cannot. PRs updated.

**Comment by kavilla** [comment]
Correct! When I have allocation I will try to get that functionality in here: https://github.com/opensearch-project/OpenSearch-Dashboards/issues/1398

**Comment by anirudha** [comment]
we will convert from alpha1 to Rc after core is done with the change.
