### ISSUE TITLE
Ensure reports-scheduler and dashboards-reports backwards compatibility with ODFE

### ISSUE THREAD

**Issue by dblock** [opensearch-project/dashboards-reports#38]
Coming from [opensearch-plugins#12](https://github.com/opensearch-project/opensearch-plugins/issues/12), enable upgrade to OpenSearch, while supporting backward compatibility.

- [x] Rename Namespaces (e.g. `com.amazon.opendistroforelasticsearch` to `org.opensearch`)
- [x] Rename Classes, Methods, Variables 
- [x] Rename Remaining Identifiers (e.g. `Opendistro` to `OpenSearch`).
- [x] Rename, and Backwards Compatibility for Rest APIs
- [x] Rename, and Backwards Compatibility for Settings 
- [x] Rename, and Backwards Compatibility for Indices
- [ ] Run in a backwards compatible way on top of OpenSearch 1.0 that has joined an ES 7.10.x cluster 
- [ ] Run in a backwards compatible way on top of OpenSearch 1.0 that has joined an ODFE 1.13.x cluster 
- [ ] Drop in replacement for the Opendistro version 1.13 of the plugin

**Comment by zhongnansu** [comment]
@davidcui-amzn Can we close this issue since the PR is merged

**Comment by davidcui-amzn** [comment]
> @davidcui-amzn Can we close this issue since the PR is merged

Closed
