### ISSUE TITLE
[FEATURE] `1.x` version increment process, remove dependency zips. 

### ISSUE THREAD

**Issue by prudhvigodithi** [opensearch-project/dashboards-reports#383]
**Is your feature request related to a problem?**
The version increment PR's for `1.x` requires job-scheduler zips to be part of `reports-scheduler/src/test/resources/bwc/job-scheduler/<version>-SNAPSHOT` and `reports-scheduler/src/test/resources/job-scheduler/` folder.
Sample PR:
https://github.com/opensearch-project/dashboards-reports/pull/366/files

**What solution would you like?**
Remove the injection of zip file via PR and use available `latest` URL to download the required zips
Example URL: https://ci.opensearch.org/ci/dbc/distribution-build-opensearch/1.3.1/latest/linux/x64/builds/opensearch/plugins/opensearch-job-scheduler-1.3.1.0.zip
This is already the case of version increments for `2.x` the zips are not added as part of PR
Example `2.x` version increment PR : https://github.com/opensearch-project/dashboards-reports/pull/371/files

**What alternatives have you considered?**
`https://ci.opensearch.org/ci/dbc/distribution-build-opensearch/<version>/latest/linux/x64/builds/opensearch/plugins/<plugin name + version>.zip` where `<version>` and `plugin name` parameter can be injected using gradle properties.

**Do you have any additional context?**
Committing a zip via a PR limits the capabilities to perform auto increment PR, more details on https://github.com/opensearch-project/opensearch-build/issues/1375

**Comment by prudhvigodithi** [comment]
Hey @anirudha @joshuali925 can you take a look at this issue.
@bbarani

**Comment by prudhvigodithi** [comment]
Hey @anirudha @joshuali925 can you take a look at this, would really help for upcoming 1.3.5 release.
Solving this issue and back-porting the PR https://github.com/opensearch-project/dashboards-reports/pull/391 to 1.3 should remove manual version increment PR's.
Thank you

**Comment by prudhvigodithi** [comment]
Hey the version increment PR for 1.3.5 https://github.com/opensearch-project/dashboards-reports/pull/420, has to have the plugin zip checked in every-time, its hard moving forward with this manual process, can someone please take a look at this issue.
Thank you
@bbarani @dblock @joshuali925 @anirudha

**Comment by prudhvigodithi** [comment]
Hey @joshuali925 and @anirudha can you please post an update on this, this is pending to close the associated [META issue](https://github.com/opensearch-project/opensearch-build/issues/1375).
Thank you

**Comment by joshuali925** [comment]
> Hey the version increment PR for 1.3.5 https://github.com/opensearch-project/dashboards-reports/pull/420, has to have the plugin zip checked in every-time, its hard moving forward with this manual process, can someone please take a look at this issue.

future PRs like #420 won't need plugin zip checked anymore in because #422 is merged. do we still need 1.x?

**Comment by prudhvigodithi** [comment]
Thanks @joshuali925 we dont need it as 1.3.x is the last supported version for 1.x. Closing this issue, we can reopen if required.
Thank you
