### ISSUE TITLE
Implement OpenSearch core branching strategy

### ISSUE THREAD

**Issue by prudhvigodithi** [opensearch-project/dashboards-reports#396]
### Description

Ensure `MAJOR_VERSION.x` branch exists, the `main` branch acts as source of truth effectively working on 2 versions at the same time.

### Related META issue

https://github.com/opensearch-project/opensearch-plugins/issues/142

### Current Behavior

Currently plugins follow a branching strategy where they work on `main` for the next development iteration, effectively working on 2 versions at the same time. This is not always true for all plugins, the release branch or branch pattern is not consistent, the lack of this standardization would limit multiple automation workflows and alignment with core repo. More details on [META ISSUE](https://github.com/opensearch-project/opensearch-plugins/issues/142)

### Proposed solution

Follow OpenSearch [core branching](https://github.com/opensearch-project/.github/blob/main/RELEASING.md#opensearch-branching). Create `1.x` and `2.x` branches, do not create `2.0` as a branch of main, instead create `main -> 2.x -> 2.0`. Maintain working CI for 3 releases at any given time.

**Comment by prudhvigodithi** [comment]
Hey @anirudha @joshuali925 can you please post an update on this branching strategy?
Thank you
@dblock @bbarani @CEHENKLE

**Comment by ps48** [comment]
Updated 1.x and created 2.x from main.

**Comment by ps48** [comment]
@prudhvigodithi waiting for job-scheduler to merge in 3.0

**Comment by dblock** [comment]
The job-scheduler issue was fixed, see https://github.com/opensearch-project/job-scheduler/pull/242.

**Comment by dblock** [comment]
There should be nothing blocking this rn. To close this issue:

- [ ] main is building 3.0
- [ ] 2.x is building next 2.x, which is currently 2.4.0
- [ ] 2.3 is building next 2.3, which is 2.3.1
- [ ] manifests in https://github.com/opensearch-project/opensearch-build/tree/main/manifests include all 3

**Comment by rupal-bq** [comment]
Status:

- [ ]  main is building 3.0 -> Currently fails at bwc testing stage.
   - [ ] 3.0.0 build fails due to upstream changes from common utils: [#281](https://github.com/opensearch-project/common-utils/pull/281)
- [x] 2.x is building next 2.x, which is currently 2.4.0
- [x] 2.3 is building next 2.3, which is 2.3.1
- [ ] manifests in https://github.com/opensearch-project/opensearch-build/tree/main/manifests include all 3
  - [x] manifests update in 2.4.0

**Comment by bbarani** [comment]
@ps48 Re-tagging this issue to 2.4.0 version.

**Comment by ps48** [comment]
All the branches are updated and merged with manifests.
