### ISSUE TITLE
Improve PDF report quality

### ISSUE THREAD

**Issue by zhongnansu** [opensearch-project/dashboards-reports#45]
**Is your feature request related to a problem? Please describe.**

**Describe the solution you'd like**

**Describe alternatives you've considered**

**Additional context**

---

I'm testing the PDF reporting functionality (my main reason to migrate to Opendistro) when I noticed that the generated PDF is just a screenshot of the page instead of a vector/text PDF. Also there's a issue with some fonts with wrong kerning.

I've reading the code and doing some tests, and looks viable to remove the screenshot part of the code:

https://github.com/opendistro-for-elasticsearch/kibana-reports/blob/98750bee4fcf64b1c4505d9f39e8b5908a95de3a/kibana-reports/server/routes/utils/visual_report/visualReportHelper.ts#L170-L177

So the quality is restored, but the font kerning issue persists. Doing some research, found [this issue on puppeteer](https://github.com/puppeteer/puppeteer/issues/2410) that suggests adding `--font-render-hinting=none` to args solves the problem. I did tested here, and the result is a perfect PDF.

Note that since the removed piece of code is responsible for adding the header and footer to the report, we need to rewrite the `composeReportHtml` to modify the original html instead of creating a new one.

I'm working on a pull request to solve this issue, but would be great to hear from someone that wrote the screenshot part the reasons for it.

**This issue is originally submitted by @iget-master**
https://github.com/opendistro-for-elasticsearch/kibana-reports/issues/350

**Comment by iget-master** [comment]
Hi @zhongnansu the related PR will be moved too?

**Comment by zhongnansu** [comment]
> Hi @zhongnansu the related PR will be moved too?

I dont think there's a way to move PR between two org, I'd appreciate if you can post a PR here. But let me know if you have difficulty with that, we can figure out something else.
