### ISSUE TITLE
[BUG] Adding unicode or emoji to header or footer doesn't render.

### ISSUE THREAD

**Issue by stockholmux** [opensearch-project/dashboards-reports#69]
**Describe the bug**
Unicode entered as markdown content is rendered as empty rectangles in resulting PDF.

**To Reproduce**
1. Create a report
2. Add visualization, etc. 
3. Click "add header"
3. In the header add some emoji or high unicode (I used "🤷‍♂️ m̩ n̩ l̩ 🤦‍♂️") - they show up properly in the "preview"
4. Download the report and see the empty rectangles (see screen shot)

**Expected behavior**
Character render properly as in preview

**Plugins**
All OpenSearch plugins

**Screenshots**
<img width="720" alt="Screen Shot 2021-06-03 at 3 33 31 PM" src="https://user-images.githubusercontent.com/1152927/120715729-422d7500-c482-11eb-8d7e-175ffd19b8fc.png">

**Host/Environment (please complete the following information):**
 - OS: MacOs
 - Version Chrome / 90.0.4430.212 (Official Build) (x86_64)
 - OpenSearch 1.0-RC1

**Comment by davidcui1225** [comment]
Added workaround with font package installation recommendations- will also track effort to auto-install popular font dependencies
