### ISSUE TITLE
Change OpenSearch Reports APIs for Notifications Integration

### ISSUE THREAD

**Issue by davidcui1225** [opensearch-project/dashboards-reports#78]

**Comment by thohn** [comment]
Hi, I'm looking to confirm if this activity is a part of the https://github.com/opensearch-project/notifications/issues/181 feature and is targeted for the OpenSearch 1.1 release in August based on the current roadmap.

We are very interested in being able to include generated reports triggered on schedule to email recipients.

**Comment by davidcui-amzn** [comment]
> Hi, I'm looking to confirm if this activity is a part of the [opensearch-project/notifications#181](https://github.com/opensearch-project/notifications/issues/181) feature and is targeted for the OpenSearch 1.1 release in August based on the current roadmap.
> 
> We are very interested in being able to include generated reports triggered on schedule to email recipients.

Yes, this activity and others within the Reporting Integration Epic are part of the Notifications feature
