### ISSUE TITLE
Make Frontend Changes to Reporting for Notifications Integration

### ISSUE THREAD

**Issue by davidcui1225** [opensearch-project/dashboards-reports#80]

**Comment by zhongnansu** [comment]
@anirudha @davidcui-amzn Should we have some special labels for all these dev tasks(coming from team originally)? Otherwise it always mixes when new exteral issues comes in. People submitting them usually don't attach label

**Comment by davidcui-amzn** [comment]
> @anirudha @davidcui-amzn Should we have some special labels for all these dev tasks(coming from team originally)? Otherwise it always mixes when new exteral issues comes in. People submitting them usually don't attach label

Is it confusing currently? I feel if we view issues from the Epics that we create, we can filter just our tasks. I feel we should not introduce a label that separates our tasks from the rest of the open source community's. Thoughts?

**Comment by zhongnansu** [comment]
@davidcui-amzn Yes we can view issues from Epics. When external issues coming in and I am trying to follow up on them from the github issue, it's mixed with our dev tasks. I can't easily find them by just a glance. I have to check each every title and check the creator to tell which one is ours and which one is from external. Just not convenient for our issue handling
